// This code (game.js) was generated by Gemini,
// a large language model from Google, on Mon Jul 28 11:02:56 2025
//
// This code was created based on user prompts from Gever Tulley.
// Refactored on Tue Jul 29 06:18:03 2025.

(function() {
    'use strict';

    const splashScreen = document.getElementById('splash-screen');
    const canvas = document.getElementById('gameCanvas');
    const ctx = canvas.getContext('2d');

    function runGame() {
        const G = 60000;
        const ROCKET_MULTIPLIER = 2;
        const PAR_MULTIPLIER = 1.25;
        const STAR_COUNT = 200;
        const MAX_TRAIL_POINTS = 10000;
        const UI_AREA_HEIGHT = 50; // Added constant for UI height

        // Player movement constants
        const MIN_MOVE = 2;
        const MAX_MOVE = 10;
        const ROCKET_LIFESPAN_MS = 8000;
        const PARTICLE_COUNT = 10;
        const PARTICLE_DURATION_MS = 750;
        const ROUND_END_DELAY_MS = 1000;
        
        const LCARS_COLORS = {
            ORANGE: '#ff9900',
            BLUE: '#9999ff',
            RED_WARNING: '#cc3333',
            TEXT: '#000000'
        };

        const PLANET_STATUS = {
            INFECTED: 'infected',
            CURED: 'cured',
            HEALTHY: 'healthy'
        };

        let lastTime = 0;
        let planets = [];
        let rockets = [];
        let trailPoints = [];
        let particles = [];
        let stars = [];

        // Game State
        let gameState = 'playing'; // 'playing', 'round_ending', 'round_over', 'game_over'
        let roundEndTimer = 0;
        let roundNumber = 1;
        let totalScore = 0;
        let infectedPlanetCount = 0;
        let rocketsLeft = 0;
        let initialRockets = 0;
        let currentPar = 0;

        const player = {
            x: 40,
            y: 0,
            size: 25,
            color: '#66aaff'
        };

        class Rocket {
            constructor(x, y) {
                this.x = x;
                this.y = y;
                this.vx = 200;
                this.vy = 0;
                this.color = player.color;
                this.life = ROCKET_LIFESPAN_MS;
                this.exploded = false;
            }

            update(dt, planets) {
                this.life -= dt * 1000;
                if (this.life <= 0) {
                    if (!this.exploded && this.x > 0 && this.x < canvas.width && this.y > 0 && this.y < canvas.height) {
                        createExplosion(this.x, this.y, '#ffff00');
                        this.exploded = true;
                    }
                    return;
                }

                planets.forEach(p => {
                    if (this.life <= 0) return;
                    const dx = p.x - this.x;
                    const dy = p.y - this.y;
                    const distSq = dx * dx + dy * dy;

                    if (distSq < (p.radius * p.radius)) {
                        if (p.status === PLANET_STATUS.INFECTED) {
                            p.status = PLANET_STATUS.CURED;
                            createExplosion(this.x, this.y, '#66aaff');
                        } else if (p.status === PLANET_STATUS.HEALTHY) {
                            createExplosion(this.x, this.y, '#ff4444');
                        }
                        this.life = 0;
                        return;
                    }

                    const force = G * p.mass / distSq;
                    const dist = Math.sqrt(distSq);
                    this.vx += (force * (dx / dist)) * dt;
                    this.vy += (force * (dy / dist)) * dt;
                });

                this.x += this.vx * dt;
                this.y += this.vy * dt;
            }

            draw(ctx) {
                ctx.fillStyle = this.color;
                ctx.fillRect(this.x, this.y, 2, 2);
            }
        }
        
        function createStars() {
            stars = [];
            for (let i = 0; i < STAR_COUNT; i++) {
                stars.push({
                    x: Math.random() * canvas.width,
                    y: Math.random() * canvas.height,
                    size: Math.random() * 2 + 1,
                    alpha: Math.random() * 0.5 + 0.2
                });
            }
        }

        function createPlanet(status) {
            const mass = 80 + Math.random() * 70;
            return {
                x: canvas.width * 0.3 + Math.random() * canvas.width * 0.6,
                y: canvas.height * 0.1 + Math.random() * canvas.height * 0.8,
                mass: mass,
                radius: mass / 7,
                status: status
            };
        }

        function createExplosion(x, y, color) {
            for (let i = 0; i < PARTICLE_COUNT; i++) {
                const angle = Math.random() * Math.PI * 2;
                const speed = Math.random() * 20 + 10;
                particles.push({
                    x: x,
                    y: y,
                    vx: Math.cos(angle) * speed,
                    vy: Math.sin(angle) * speed,
                    color: color,
                    alpha: 1,
                    decayRate: 1000 / PARTICLE_DURATION_MS
                });
            }
        }

        function newRound() {
            const baseProgression = 2 + Math.floor((roundNumber - 1) / 3);
            infectedPlanetCount = (baseProgression >= 6) ? (3 + Math.floor(Math.random() * 4)) : baseProgression;

            initialRockets = ROCKET_MULTIPLIER * infectedPlanetCount;
            currentPar = Math.ceil(PAR_MULTIPLIER * infectedPlanetCount);
            rocketsLeft = initialRockets;

            rockets = [];
            planets = [];
            trailPoints = [];
            particles = [];

            for (let i = 0; i < infectedPlanetCount; i++) {
                planets.push(createPlanet(PLANET_STATUS.INFECTED));
            }

            if (roundNumber > 3) {
                const healthyPlanetCount = Math.floor(Math.random() * 3);
                for (let i = 0; i < healthyPlanetCount; i++) {
                    planets.push(createPlanet(PLANET_STATUS.HEALTHY));
                }
            }
            gameState = 'playing';
        }

        function launchRocket() {
            if (rocketsLeft <= 0 || gameState !== 'playing') return;
            rocketsLeft--;
            rockets.push(new Rocket(player.x + player.size, player.y));
        }

        function checkRoundStatus() {
            const stillInfected = planets.filter(p => p.status === PLANET_STATUS.INFECTED).length;

            if (stillInfected === 0) {
                const rocketsUsed = initialRockets - rocketsLeft;
                const roundScore = rocketsUsed - currentPar;
                totalScore += roundScore;
                gameState = 'round_ending';
                roundEndTimer = ROUND_END_DELAY_MS;
            } else if (rocketsLeft === 0 && rockets.length === 0) {
                const rocketsUsed = initialRockets;
                const roundScore = rocketsUsed - currentPar;
                totalScore += roundScore;
                gameState = 'game_over';
            }
        }

        function updateParticles(dt) {
             particles.forEach(p => {
                p.alpha -= p.decayRate * dt;
                p.x += p.vx * dt;
                p.y += p.vy * dt;
            });
            particles = particles.filter(p => p.alpha > 0);
        }

        function update(deltaTime) {
            if (!deltaTime) return;
            const dt = deltaTime / 1000;
            
            updateParticles(dt);

            if (gameState === 'round_ending') {
                roundEndTimer -= deltaTime;
                if (roundEndTimer <= 0) {
                    gameState = 'round_over';
                }
                return;
            }

            if (gameState !== 'playing') return;

            rockets.forEach(r => {
                r.update(dt, planets);
                trailPoints.push({ x: r.x, y: r.y, color: r.color });
            });
            
            while (trailPoints.length > MAX_TRAIL_POINTS) {
                trailPoints.shift();
            }
            
            rockets = rockets.filter(r => r.life > 0);
            checkRoundStatus();
        }

        function drawOverlay(title, ...lines) {
            ctx.fillStyle = 'rgba(0, 0, 0, 0.7)';
            ctx.fillRect(0, 0, canvas.width, canvas.height);

            ctx.fillStyle = 'white';
            ctx.textAlign = 'center';
            ctx.font = '48px "Courier New"';
            ctx.fillText(title, canvas.width / 2, canvas.height / 2 - 120);

            ctx.font = '24px "Courier New"';
            lines.forEach((line, i) => {
                ctx.fillText(line, canvas.width / 2, canvas.height / 2 - 40 + (i * 35));
            });
        }
        
        function drawLcarsUI() {
            const barHeight = 30;
            const cornerRadius = 15;
            const padding = 10;
            
            // --- Left element ---
            ctx.fillStyle = LCARS_COLORS.ORANGE;
            ctx.beginPath();
            ctx.moveTo(0, 0);
            ctx.lineTo(420, 0);
            ctx.lineTo(420, barHeight);
            ctx.lineTo(padding, barHeight);
            ctx.arcTo(0, barHeight, 0, barHeight + padding, cornerRadius);
            ctx.lineTo(0, barHeight + cornerRadius);
            ctx.closePath();
            ctx.fill();

            // --- UPDATED: Split right-side bar into two sections ---

            // 1. ROCKETS section background
            let rocketBgColor = LCARS_COLORS.BLUE;
            if (rocketsLeft === 2) {
                rocketBgColor = '#dddd00';
            } else if (rocketsLeft < 2) {
                rocketBgColor = LCARS_COLORS.RED_WARNING;
            }
            ctx.fillStyle = rocketBgColor;
            ctx.fillRect(canvas.width - 240, 0, 120, barHeight);

            // 2. INFECTED section background (always blue)
            ctx.fillStyle = LCARS_COLORS.BLUE;
            const infectedBarX = canvas.width - 120;
            ctx.beginPath();
            ctx.moveTo(infectedBarX, 0);
            ctx.lineTo(canvas.width - cornerRadius, 0);
            ctx.arcTo(canvas.width, 0, canvas.width, cornerRadius, cornerRadius);
            ctx.lineTo(canvas.width, barHeight);
            ctx.lineTo(infectedBarX, barHeight);
            ctx.closePath();
            ctx.fill();

            // --- Draw Text on UI elements ---
            ctx.font = 'bold 16px "Courier New"';
            let scoreDisplay = totalScore > 0 ? `+${totalScore}` : (totalScore === 0 ? 'E' : totalScore);

            // Left side text
            ctx.fillStyle = LCARS_COLORS.TEXT;
            ctx.textAlign = 'left';
            ctx.fillText(`ROUND: ${roundNumber}`, padding * 2, 20);
            ctx.fillText(`PAR: ${currentPar}`, 170, 20);
            ctx.fillText(`SCORE: ${scoreDisplay}`, 300, 20);

            // Right side text
            ctx.textAlign = 'right';
            const stillInfectedCount = planets.filter(p => p.status === PLANET_STATUS.INFECTED).length;
            
            // --- UPDATED: Text color logic for rocket count ---
            let rocketTextColor = LCARS_COLORS.TEXT; // Default black
            if (rocketsLeft === 0) {
                rocketTextColor = '#ffffff'; // White when 0
            }
            ctx.fillStyle = rocketTextColor;
            ctx.fillText(`ROCKETS: ${rocketsLeft}`, canvas.width - padding - 120, 20);
            
            // Reset to default for other text
            ctx.fillStyle = LCARS_COLORS.TEXT; 
            ctx.fillText(`INFECTED: ${stillInfectedCount}`, canvas.width - padding, 20);
        }

        function render() {
            ctx.fillStyle = '#080810';
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            
            stars.forEach(s => {
                ctx.fillStyle = `rgba(255, 255, 255, ${s.alpha})`;
                ctx.fillRect(s.x, s.y, s.size, s.size);
            });

            ctx.fillStyle = '#0000ff';
            trailPoints.forEach(p => {
                ctx.fillRect(p.x, p.y, 4, 4);
            });

            ctx.fillStyle = player.color;
            ctx.beginPath();
            ctx.moveTo(player.x + player.size, player.y);
            ctx.lineTo(player.x, player.y - player.size / 2);
            ctx.lineTo(player.x, player.y + player.size / 2);
            ctx.closePath();
            ctx.fill();

            planets.forEach(p => {
                switch (p.status) {
                    case PLANET_STATUS.INFECTED: ctx.fillStyle = '#ffaa66'; break;
                    case PLANET_STATUS.CURED:    ctx.fillStyle = '#66ffaa'; break;
                    case PLANET_STATUS.HEALTHY:  ctx.fillStyle = '#88ddff'; break;
                }
                ctx.beginPath();
                ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
                ctx.fill();
            });

            rockets.forEach(r => r.draw(ctx));

            particles.forEach(p => {
                ctx.fillStyle = p.color;
                ctx.globalAlpha = p.alpha;
                ctx.fillRect(p.x - 1, p.y - 1, 2, 2);
                ctx.globalAlpha = 1;
            });
            
            drawLcarsUI();

            if (gameState === 'round_over') {
                const rocketsUsed = initialRockets - rocketsLeft;
                const roundScore = rocketsUsed - currentPar;
                let roundScoreDisplay = roundScore > 0 ? `+${roundScore}` : `${roundScore}`;
                if (roundScore === 0) roundScoreDisplay = 'E';
                
                drawOverlay(`Round ${roundNumber} Complete!`, 
                    `Par: ${currentPar}`, 
                    `Shots: ${rocketsUsed}`,
                    `Score: ${roundScoreDisplay}`,
                    '', 
                    'Click or press Space to continue...');
            } else if (gameState === 'game_over') {
                const scoreDisplay = totalScore > 0 ? `+${totalScore}` : (totalScore === 0 ? 'E' : totalScore);
                drawOverlay('Game Over', `You reached Round ${roundNumber}.`, `Final Score: ${scoreDisplay}`, '', 'Click or press Space to play again.');
            }
        }
        
        function gameLoop(timestamp) {
            const deltaTime = timestamp - lastTime;
            lastTime = timestamp;
            update(deltaTime);
            render();
            requestAnimationFrame(gameLoop);
        }

        function handleAdvance() {
            if (gameState === 'round_over') {
                roundNumber++;
                newRound();
            } else if (gameState === 'game_over') {
                roundNumber = 1;
                totalScore = 0;
                newRound();
            }
        }

        function resize() {
            canvas.width = window.innerWidth;
            canvas.height = window.innerHeight;
            player.y = canvas.height / 2;
            roundNumber = 1;
            totalScore = 0;
            createStars();
            newRound();
        }
        
        window.addEventListener('keydown', e => {
            if (e.code === 'Space' && e.target === document.body) {
                e.preventDefault();
                if (gameState === 'playing') {
                    launchRocket();
                } else if (gameState !== 'round_ending'){
                    handleAdvance();
                }
            } else if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
                e.preventDefault();
                const moveDistance = e.shiftKey ? MAX_MOVE : MIN_MOVE;
                player.y += (e.key === 'ArrowUp' ? -moveDistance : moveDistance);
                player.y = Math.max(UI_AREA_HEIGHT + player.size / 2, Math.min(canvas.height - player.size / 2, player.y));
            }
        });

        canvas.addEventListener('click', () => {
             if (gameState !== 'round_ending') {
                handleAdvance();
             }
        });
        window.addEventListener('resize', resize);
        
        resize();
        requestAnimationFrame(gameLoop);
    }
    
    function startGame(e) {
        e.preventDefault();
        splashScreen.style.display = 'none';
        canvas.style.display = 'block';
        runGame();
    }
    
    splashScreen.addEventListener('click', startGame, { once: true });
    window.addEventListener('keydown', (e) => {
        if (e.code === 'Space') {
            startGame(e);
        }
    }, { once: true });

})();
