10 REM INSTR TEST
20 PRINT "TEST 1: INSTR('ABC', 'A') = 1 ";
30 I = INSTR("ABC", "A")
40 IF I = 1 THEN PRINT "[PASS]" ELSE PRINT "[FAIL] " ; I
50 PRINT "TEST 2: INSTR('ABC', 'B') = 2 ";
60 I = INSTR("ABC", "B")
70 IF I = 2 THEN PRINT "[PASS]" ELSE PRINT "[FAIL] " ; I
80 PRINT "TEST 3: INSTR('ABC', 'D') = 0 ";
90 I = INSTR("ABC", "D")
100 IF I = 0 THEN PRINT "[PASS]" ELSE PRINT "[FAIL] " ; I
110 PRINT "TEST 4: INSTR(2, 'ABC', 'A') = 0 ";
120 I = INSTR(2, "ABC", "A")
130 IF I = 0 THEN PRINT "[PASS]" ELSE PRINT "[FAIL] " ; I
140 PRINT "TEST 5: INSTR(2, 'ABC', 'B') = 2 ";
150 I = INSTR(2, "ABC", "B")
160 IF I = 2 THEN PRINT "[PASS]" ELSE PRINT "[FAIL] " ; I
170 PRINT "TEST 6: INSTR(3, 'ABCABC', 'A') = 4 ";
180 I = INSTR(3, "ABCABC", "A")
190 IF I = 4 THEN PRINT "[PASS]" ELSE PRINT "[FAIL] " ; I
200 END
